language: r
sudo: required
warnings_are_errors: true

env:
 global:
   - CRAN: http://cran.rstudio.com
   - r_check_args="--no-vignettes --no-build-vignettes"

before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr
after_success:
  - Rscript -e 'covr::codecov()'
